In [9]:
#安装必需库
!pip install wrds pandas

Requirement already satisfied: wrds in d:\anaconda\lib\site-packages (3.5.0)
Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.2.3)
Requirement already satisfied: ipython<=9.8.0 in d:\anaconda\lib\site-packages (from wrds) (9.7.0)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in d:\anaconda\lib\site-packages (from wrds) (2.9.11)
Requirement already satisfied: sqlalchemy<2.1,>=2 in d:\anaconda\lib\site-packages (from wrds) (2.0.43)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: colorama>=0.4.4 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.5 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in d:\anaconda\lib\site-packages (from ipython<=9.8.0->wrds) (5.14.3)
Requirement already satisfied: wcwidth in d:\anaconda\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython<=9.8.0->wrds) (0.2.13)
Requirement already satisfied: greenlet>=1 in d:\anaconda\lib\site-packages (from sqlalchemy<2.1,>=2->wrds) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\anaconda\lib\site-packages (from sqlalchemy<2.1,>=2->wrds) (4.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in d:\anaconda\lib\site-packages (from jedi>=0.18.1->ipython<=9.8.0->wrds) (0.8.5)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython<=9.8.0->wrds) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython<=9.8.0->wrds) (3.0.0)
Requirement already satisfied: pure_eval in d:\anaconda\lib\site-packages (from stack_data>=0.6.0->ipython<=9.8.0->wrds) (0.2.3)

In [8]:
#导入库
import wrds
import pandas as pd

In [10]:
#连接 WRDS
db = wrds.Connection(wrds_username="yuxuanhuang")

Loading library list...
Done

In [15]:
#获取苹果公司年度数据
sql_query = """
    SELECT tic, fyear, at, sale, ni
    FROM comp.funda
    WHERE tic = 'AAPL'
    AND fyear >= 2010
    ORDER BY fyear;
"""

# 执行查询
df = db.raw_sql(sql_query)

# 显示前5行
df.head()

    tic  fyear        at      sale       ni
0  AAPL   2010   75183.0   65225.0  14013.0
1  AAPL   2010      <NA>      <NA>     <NA>
2  AAPL   2011  116371.0  108249.0  25922.0
3  AAPL   2011      <NA>      <NA>     <NA>
4  AAPL   2012      <NA>      <NA>     <NA>

In [16]:
#基础查看
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   tic     32 non-null     string
 1   fyear   32 non-null     Int64
 2   at      26 non-null     Float64
 3   sale    26 non-null     Float64
 4   ni      26 non-null     Float64
dtypes: Float64(3), Int64(1), string(1)
memory usage: 1.5 KB

          fyear             at           sale            ni
count      32.0           26.0           26.0          26.0
mean     2017.5  311858.692308  281053.846154       66866.5
std    4.683533   81522.570074  100625.894159  28363.514665
min      2010.0        75183.0        65225.0       14013.0
25%     2013.75       321686.0      218626.75       46353.0
50%      2017.5       351002.0       265359.0       57411.0
75%     2021.25       359241.0       383285.0       94680.0
max      2025.0       375319.0       416161.0      112010.0

In [17]:
# 保存数据为 CSV 文件
df.to_csv("AAPL_WRDS_Financial_Data.csv", index=False)

print("CSV 文件已保存！")

CSV 文件已保存！